name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
      
    - name: Checkout Project
      uses: actions/checkout@v1

    - name: Run Build
      run: swift build
